### ISSUE TITLE
mac下的homebrew不允许使用sudo模式安装了

### ISSUE THREAD

**Issue by winglight** [foolcage/fooltrader#27]
第一步的初始化环境就过不去了，错误如下：
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by winglight** [comment]
这是自动安装virtualenv时报的错，我手动安装之后，报了新的错：
Running virtualenv with interpreter ～/anaconda3/bin/python3
Fatal Python error: Py_Initialize: unable to load the file system codec
LookupError: no codec search functions registered: can't find encoding
 
Current thread 0x00007fffdc9dc3c0 (most recent call first):

**Comment by foolcage** [comment]
@winglight 建议用ubuntu,目前来说mac,windows是有各种奇怪的问题.

**Comment by winglight** [comment]
@foolcage 环境建多了，切换起来比较麻烦啊。。。

我看readme里提到，在mac上测试过，是不是已经有成功案例了呢？

**Comment by foolcage** [comment]
@winglight 我之前在mac,ubuntu两边一起开发,但现在mac用得比较少了.更新后,可能有些问题.
晚点用pipenv来统一下吧.

**Comment by winglight** [comment]
@foolcage mac上很多坑啊，es和kibana都安装好了，但是项目下面各种基本操作都走不通：
1.先在工程下面运行：source ve/bin/activate，然后再跑schedule就不行了
···
python fooltrader/sched/sched_stock_meta.py
Traceback (most recent call last):
  File "fooltrader/sched/sched_stock_meta.py", line 7, in <module>
    from fooltrader.connector import es_connector
ModuleNotFoundError: No module named 'fooltrader'
···
2.这是另一个错误：
···
from fooltrader.connector import es_connector
from: can't read /var/mail/fooltrader.connector
···
这总不至于是写死的路径吧？
