### ISSUE TITLE
ImportError: No module named 'pandas'

### ISSUE THREAD

**Issue by idiomer** [foolcage/fooltrader#3]
按readme step-by-step后，在4.3节中from fooltrader.datamanager import datamanager时，报错ImportError: No module named 'pandas'
     是否因为./init_env.sh的时候没有将那些package install在ve里面？

备注：系统ubuntu 16.04

**Comment by foolcage** [comment]
取定4.2看到了:
Requirements installed.  
env ok
确定执行了:
$ source ve/bin/activate
$ ./ve/bin/ipython

截图看一下呢?
pycharm环境如果设置为相同的ve,应该所有的编译运行都是OK才是对的.

**Comment by idiomer** [comment]
Requirements installed.
env ok
确认看到了。终端已经关闭，截不到图了

![image](https://user-images.githubusercontent.com/17400651/37147437-e07691c2-2301-11e8-8bbb-071db9851890.png)

**Comment by idiomer** [comment]
在没有开启ve环境，直接用ipython的时候直接运行，如下。
![image](https://user-images.githubusercontent.com/17400651/37147971-af71a178-2303-11e8-944a-68b4dc5b229c.png)
是否py没有加#coding: utf-8 的原因？

**Comment by foolcage** [comment]
![pip_show](https://user-images.githubusercontent.com/1160499/37150129-6e36e53a-230b-11e8-8448-708eadeb5a0e.png)
在ve环境下pip show一下呢?
如果确实没装好,建议在ve环境下用pip重新装一下.

**Comment by foolcage** [comment]
编码的问题 由于我环境默认都是utf8 没注意到
```
$  echo $LANG
$ en_US.UTF-8
```
建议使用纯utf8环境
https://perlgeek.de/en/article/set-up-a-clean-utf8-environment
