### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'

### ISSUE THREAD

**Issue by idiomer** [foolcage/fooltrader#7]
hi, foolcage:
  通过pip install的方式安装后，执行from fooltrader.datamanager import datamanager，报错没有fooltrader.spiders.america，然后cd到fooltrader/spiders/里面发现确实没有america这个文件夹或py文件。但在git上是有的。
  于是采用了git clone的方式step-by-step安装，并设置了 export FOOLTRADER_STORE_PATH=`pwd`，之后在ipython和python3.5中执行from fooltrader.datamanager import datamanager，都报错AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'，截图如下：
![image](https://user-images.githubusercontent.com/17400651/37508004-20f56bf8-292c-11e8-838d-259d835d25de.png)
![image](https://user-images.githubusercontent.com/17400651/37508020-30ca4e36-292c-11e8-9416-b461aa3c36c3.png)

**Comment by foolcage** [comment]
建议:
删掉ve
ubuntu package能升级的都升一下
把init.sh里面的这句改一下:
virtualenv -p python3 $BASEDIR/ve --system-site-packages
->
virtualenv -p python3 $BASEDIR/ve

然后重新init.sh

**Comment by idiomer** [comment]
我通过升级ve里面的pyopenssl解决了： pip install -U pyopenssl
